---
title: "R Basics"
output: html_notebook
---

## 1.1. Installing a Package
```{R}
install.packages(c("ggplot2", "gcookbook"))
```    

## 1.2. Loading a Package
```{R}
library(ggplot2)
library(gcookbook)
```    

```{R}
install.packages("ggplot2")
```

```{R}
library(ggplot2)
```

## 1.3. Loading a Delimited Text Data File
```{r}
data <- read.csv("datafile.csv")
```

```{r}
data <- read.csv("datafile.csv", header=FALSE)
```

```{r}
# Manually assign the header names
names(data) <- c("Column1","Column2","Column3")
```

```{r}
data <- read.csv("datafile.csv", sep="\t")
```

```{r}
data <- read.csv("datafile.csv", stringsAsFactors=FALSE)
```
### Convert to factor
```{r}
data$Sex <- factor(data$Sex)

str(data)
```

## 1.4. Loading Data from an Excel File


```{r}
# Only need to install once
install.packages("xlsx")

library(xslx)
data <- read.xlsx("datafile.xlsx", 1)
```

```{r}
# Only need to install once
install.packages("gdata")

library(gdata)
# Read first sheet
data <- read.xls("datafile.xls")
```

```{r}
data <- read.xlsx("datafile.xls", sheetIndex=2)

data <- read.xlsx("datafile.xls", sheetName="Revenues")
```

```{r}
data <- read.xls("datafile.xls", sheet=2)
```

```{r}
# Only need to install the first time
install.packages("foreign")

library(foreign)
data <- read.spss("datafile.sav")
```
## Discussion
The foreign package also includes functions to load from other formats, including:  
. read.octave(): Octave and MATLAB  
. read.systat(): SYSTAT  
. read.xport(): SAS XPORT  
. read.dta(): Stata  

